name = "mayachok"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "mayachok-db"
database_id = "REPLACE_WITH_D1_DATABASE_ID"

[triggers]
crons = ["17 4 * * *"]
